"use client";
import { useEffect, useMemo, useState } from "react";

type EventItem = { id: string; title: string; summary: string | null; status: string; importance_level: number; india_relevance: number; updated_at: string };
type Detail = EventItem & { incidents: { id: string; title: string; summary: string | null; created_at: string }[] };
type Claim = { claim_id: string; statement: string; type: string; confidence: string; confidence_explanation: string; document_title?: string; canonical_url?: string; source_name?: string };
type Row = Record<string, string | number | null>;
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export default function Home() {
  const [section, setSection] = useState("india");
  const [events, setEvents] = useState<EventItem[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [claims, setClaims] = useState<Claim[]>([]);
  const [changes, setChanges] = useState<Row[]>([]);
  const [history, setHistory] = useState<Row[]>([]);
  const [impact, setImpact] = useState<{ level: number; pathways: Row[]; hypotheses: Row[] }>({ level: 0, pathways: [], hypotheses: [] });
  const [contradictions, setContradictions] = useState<Row[]>([]);
  const [related, setRelated] = useState<Row[]>([]);
  const [indicators, setIndicators] = useState<Row[]>([]);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [watched, setWatched] = useState(false);
  const title = useMemo(() => ({ india: "India Relevant", global: "Global Strategic Events", other: "Other Intelligence", all: "All Intelligence" }[section] || "Intelligence"), [section]);

  useEffect(() => { setLoading(true); fetch(`${API}/events?section=${section}`).then(r => { if (!r.ok) throw new Error("API unavailable"); return r.json(); }).then((data: EventItem[]) => { setEvents(data); setError(""); if (!selected && data[0]) setSelected(data[0].id); }).catch(() => setError("Dashboard API is unavailable. Start the stack with Docker Compose.")).finally(() => setLoading(false)); }, [section]);
  useEffect(() => { if (!selected) return; Promise.all([fetch(`${API}/events/${selected}`).then(r => r.json()), fetch(`${API}/events/${selected}/evidence`).then(r => r.json()), fetch(`${API}/events/${selected}/changes`).then(r => r.json()), fetch(`${API}/events/${selected}/history`).then(r => r.json()), fetch(`${API}/events/${selected}/india-impact`).then(r => r.json()), fetch(`${API}/events/${selected}/contradictions`).then(r => r.json()), fetch(`${API}/events/${selected}/related`).then(r => r.json()), fetch(`${API}/events/${selected}/watch-indicators`).then(r => r.json())]).then(([d, c, ch, h, im, co, re, wi]) => { setDetail(d); setClaims(c); setChanges(ch); setHistory(h); setImpact(im); setContradictions(co); setRelated(re); setIndicators(wi); }).catch(() => setError("Unable to load all event intelligence.")); }, [selected]);

  async function toggleWatch() { if (!selected) return; const response = await fetch(`${API}/events/${selected}/watch`, { method: "POST" }); const data = await response.json(); setWatched(data.watched); }
  async function ask() { if (!selected || !question.trim()) return; setAnswer("Checking stored claims and sources…"); const response = await fetch(`${API}/events/${selected}/ask`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); const data = await response.json(); setAnswer(data.answer); }

  return <main className="shell">
    <aside className="rail"><div className="brand"><span className="mark">F</span><div><b>FIELDNOTE</b><small>INTELLIGENCE DESK</small></div></div><div className="rail-label">WORKSPACE</div>{[["india","India relevant"],["global","Global strategic"],["other","Other intelligence"],["all","All events"]].map(([key,label]) => <button key={key} className={`nav ${section===key?"active":""}`} onClick={() => setSection(key)}><span className="nav-dot"/>{label}</button>)}<div className="rail-bottom"><span className="pulse"/> LOCAL SYSTEM <span className="system">CONNECTED</span></div></aside>
    <section className="content"><header className="topbar"><div><span className="eyebrow">GLOBAL INTELLIGENCE / LIVE DESK</span><h1>{title}</h1></div><div className="top-meta"><span>PRIVATE WORKSPACE</span><span className="avatar">V</span></div></header>
      {error && <div className="notice">{error}</div>}
      <div className="dashboard"><section className="feed"><div className="feed-head"><span>EVENT THREADS <b>{events.length.toString().padStart(2,"0")}</b></span><span>UPDATED RECENTLY</span></div>{loading ? <div className="empty">Loading intelligence…</div> : events.length===0 ? <div className="empty"><b>No event threads yet</b><p>New discoveries appear here after the first collection run.</p><button className="text-button" onClick={() => fetch(`${API}/collection/run`,{method:"POST"}).then(()=>location.reload())}>Run collection now ↗</button></div> : events.map((event,index)=><button key={event.id} className={`event-card ${selected===event.id?"selected":""}`} onClick={()=>setSelected(event.id)}><div className="card-top"><span className={`status ${event.status.toLowerCase()}`}>{event.status.replaceAll("_"," ")}</span><span className="rank">{String(index+1).padStart(2,"0")}</span></div><h2>{event.title}</h2><p>{event.summary}</p><div className="card-foot"><span>{event.india_relevance ? <><i className="india-dot"/> INDIA RELEVANCE {event.india_relevance}/4</> : "GLOBAL MONITOR"}</span><span>IMPORTANCE {event.importance_level}/5</span></div></button>)}</section>
      <section className="detail">{detail ? <><div className="detail-top"><span>EVENT THREAD / {detail.id.slice(0,8).toUpperCase()}</span><button className="watch" onClick={toggleWatch}>{watched?"★ WATCHING":"☆ WATCH"}</button></div><h2 className="detail-title">{detail.title}</h2><p className="lede">{detail.summary || "No event summary has been recorded yet."}</p><div className="facts"><div><small>STATUS</small><b>{detail.status.replaceAll("_"," ")}</b></div><div><small>IMPORTANCE</small><b>{detail.importance_level} / 5</b></div><div><small>INDIA RELEVANCE</small><b>{detail.india_relevance} / 4</b></div></div>
        <div className="section-head"><h3>Incident timeline</h3><span>{detail.incidents?.length || 0} INCIDENTS</span></div><div className="timeline">{detail.incidents?.length ? detail.incidents.map(incident=><div className="timeline-item" key={incident.id}><span className="timeline-mark"/><small>{new Date(incident.created_at).toLocaleString()}</small><b>{incident.title}</b><p>{incident.summary}</p></div>) : <p className="muted">No incidents recorded.</p>}</div>
        <div className="section-head"><h3>What changed</h3><span>{changes.length} UPDATES</span></div><div className="timeline">{changes.length ? changes.map((row,i)=><div className="timeline-item" key={String(row.id||i)}><span className="timeline-mark"/><small>{row.created_at ? new Date(String(row.created_at)).toLocaleString() : ""}</small><b>{String(row.change_type||"UPDATE").replaceAll("_"," ")}</b><p>{row.summary}</p></div>) : <p className="muted">No material changes recorded.</p>}</div>
        <div className="section-head"><h3>India impact</h3><span>LEVEL {impact.level} / 4</span></div><div className="impact-list">{impact.pathways.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence">PATHWAY</span><b>{row.from_node} → {row.to_node}</b><p>{row.pathway_note} · {row.pathway}</p></div>)}{impact.hypotheses.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence">{row.label}</span><b>{row.statement}</b><p>{row.causal_confidence} · {row.explanation}</p></div>)}{impact.pathways.length+impact.hypotheses.length===0&&<p className="muted">No India impact pathway or causal hypothesis is stored. Relevance level alone does not establish causation.</p>}</div>
        <div className="section-head"><h3>Contradictions</h3><span>{contradictions.length} UNRESOLVED</span></div><div className="claims">{contradictions.length?contradictions.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence contested">CONTESTED</span><b>{row.claim_a}</b><p>{row.explanation}</p><b>{row.claim_b}</b></div>):<p className="muted">No explicit contradictions are recorded.</p>}</div>
        <div className="section-head"><h3>Claims & provenance</h3><span>{claims.length} CLAIMS</span></div><div className="claims">{claims.slice(0,8).map((claim,i)=><div className="claim" key={`${claim.claim_id}-${i}`}><span className={`confidence ${claim.confidence.toLowerCase()}`}>{claim.confidence}</span><b>{claim.statement}</b><p>{claim.type} · {claim.confidence_explanation}</p>{claim.source_name&&<a href={claim.canonical_url} target="_blank" rel="noreferrer">{claim.source_name} ↗</a>}</div>)}</div>
        <div className="section-head"><h3>Historical context</h3><span>{history.length} RECORDS</span></div><div className="claims">{history.length?history.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence">HISTORY</span><b>{row.title}</b><p>{row.interpretation||row.summary}</p></div>):<p className="muted">No canonical historical records are linked to this event.</p>}</div>
        <div className="section-head"><h3>Related events</h3><span>{related.length} LINKS</span></div><div className="claims">{related.length?related.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence">{row.relation}</span><b>{row.title}</b><p>{row.explanation}</p></div>):<p className="muted">No related event threads are linked.</p>}</div>
        <div className="section-head"><h3>What to watch</h3><span>{indicators.length} INDICATORS</span></div><div className="claims">{indicators.length?indicators.map((row,i)=><div className="claim" key={String(row.id||i)}><span className="confidence">WATCH</span><b>{row.indicator}</b><p>{row.why_it_matters}</p></div>):<p className="muted">No observable indicators are recorded yet.</p>}</div>
        <div className="ask-box"><span className="eyebrow">GROUNDED EVENT Q&A</span><h3>Ask this event</h3><form onSubmit={e=>{e.preventDefault();ask();}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What changed, and what evidence supports it?"/><button>ASK ↗</button></form>{answer&&<p className="answer">{answer}</p>}<small>Answers use stored claims and include source references when available.</small></div>
      </> : <div className="empty">Select an event thread to inspect its intelligence.</div>}</section></div>
    </section>
  </main>;
}
